Repository reimagined/resolve, pull requests merged in 2018-06, with the labels that each got.

#625 Feature/parallel ci
  .travis.yml
  Jenkinsfile
Labels: Component: Core, Severity: Moderate, Type: Enhancement

#633 Feature/fix warns
  packages/create-resolve-app/bin/index.js
Labels: Component: Core, Severity: Minor, Type: Enhancement

#651 Check that aggregate id is a string
  examples/todo-two-levels/client/containers/Index.js
  packages/resolve-command/src/index.js
Labels: Component: resolve-command, Severity: Minor, Type: Bug

#658 Feature/Table index improvements
  .eslintrc.js
  examples/hacker-news/common/read-models/default.projection.js
  examples/todo-two-levels/test/unit/__snapshots__/Index.test.js.snap
  examples/todo-two-levels/test/unit/__snapshots__/Todo.test.js.snap
  examples/top-list/common/read-models/rating.projection.js
  packages/readmodel-adapters/resolve-readmodel-base/src/build-projection.js
  packages/readmodel-adapters/resolve-readmodel-base/src/check-store-api.js
  packages/readmodel-adapters/resolve-readmodel-base/src/messages.js
  packages/readmodel-adapters/resolve-readmodel-base/test/check-store-api.tests.js
  packages/readmodel-adapters/resolve-readmodel-memory/src/store-api.js
  packages/readmodel-adapters/resolve-readmodel-memory/test/store-api.tests.js
  packages/readmodel-adapters/resolve-readmodel-mysql/README.md
  packages/readmodel-adapters/resolve-readmodel-mysql/package.json
  packages/readmodel-adapters/resolve-readmodel-mysql/src/meta-api.js
  packages/readmodel-adapters/resolve-readmodel-mysql/src/store-api.js
  packages/readmodel-adapters/resolve-readmodel-mysql/test/meta-api.tests.js
  packages/readmodel-adapters/resolve-readmodel-mysql/test/store-api.tests.js
  packages/resolve-scripts/src/runtime/server/read_model_query_executors.js
  yarn.lock
Labels: Component: readmodel-adapters, Severity: Moderate, Type: Bug

#659 Hotfix/windows paths
  packages/resolve-scripts/src/core/get_webpack_client_config.js
  packages/resolve-scripts/src/core/get_webpack_server_config.js
Labels: Component: Core, Severity: Major, Type: Bug

#661 Hotfix/undefined env vars
  packages/resolve-scripts/src/core/env_string.js
  packages/resolve-scripts/src/core/setup.js
Labels: Component: resolve-scripts, Severity: Moderate, Type: Bug

#653 Docs/Common readme for docs
  docs/README.md
Labels: Component: Documentation, Severity: Minor, Type: Enhancement

#663 Feature/resolve scripts cli docs
  docs/API References.md
  packages/resolve-scripts/configs/cli.list.json
  packages/resolve-scripts/configs/command.list.json
  packages/resolve-scripts/src/core/commands/build.js
  packages/resolve-scripts/src/core/commands/dev.js
  packages/resolve-scripts/src/core/commands/start.js
Labels: Component: Documentation, Severity: Minor, Type: Bug

#666 Hotfix/Default status code (#645)
  packages/resolve-auth/src/createAuthOptions.js
Labels: Component: resolve-auth, Severity: Minor, Type: Bug

#652 Docs/examples
  Jenkinsfile
  examples/README.md
  examples/hacker-news/README.md
  examples/hello-world/README.md
  examples/todo-two-levels/README.md
  examples/todo/README.md
  examples/top-list/README.md
  examples/with-authentication/README.md
  examples/with-postcss-modules/README.md
  examples/with-postcss/.babelrc
  examples/with-postcss/.gitignore
  examples/with-postcss/.yarnrc
  examples/with-postcss/README.md
  examples/with-postcss/client/containers/App.css
  examples/with-postcss/client/containers/App.js
  examples/with-postcss/client/routes.js
  examples/with-postcss/package.json
  examples/with-postcss/resolve.build.config.js
  examples/with-postcss/resolve.config.json
  examples/with-postcss/test/functional/index.test.js
  examples/with-postcss/test/unit/App.test.js
  examples/with-postcss/test/unit/__snapshots__/App.test.js.snap
  examples/with-postcss/test/unit/config/jest-css-modules-transform.js
  examples/with-postcss/test/unit/config/jest-js-transform.js
  examples/with-styled-components/README.md
Labels: Component: Documentation, Severity: Moderate, Type: Enhancement

#657 Docs/query
  docs/Query.md
Labels: Component: Documentation, Severity: Moderate, Type: Enhancement

#654 Docs/Aggregate
  docs/Aggregate.md
  docs/Command.md
Labels: Component: Documentation, Severity: Moderate, Type: Enhancement
