Repository reimagined/resolve, pull requests merged in 2018-07, with the labels that each got.

#669 Docs/Review #647
  packages/create-resolve-app/README.md
  packages/resolve-scripts/README.md
  packages/resolve-scripts/configs/cli.list.json
  packages/resolve-scripts/configs/env.list.json
  packages/resolve-scripts/configs/message.json
Labels: Component: Documentation, Severity: Minor, Type: Enhancement

#634 Serverless saga
  .eslintrc.js
  examples/top-list/common/sagas/index.js
  examples/top-list/sagas/index.js
  examples/with-saga/.babelrc
  examples/with-saga/.gitignore
  examples/with-saga/.yarnrc
  examples/with-saga/README.md
  examples/with-saga/client/components/Header.js
  examples/with-saga/client/containers/App.js
  examples/with-saga/client/routes.js
  examples/with-saga/common/aggregates/user.commands.js
  examples/with-saga/common/aggregates/user.projection.js
  examples/with-saga/common/event-names.js
  examples/with-saga/common/read-models/default.projection.js
  examples/with-saga/common/read-models/default.resolvers.js
  examples/with-saga/package.json
  examples/with-saga/resolve.config.json
  examples/with-saga/sagas/index.js
  examples/with-saga/sagas/user-creation.js
  examples/with-saga/static/bootstrap.min.css
  examples/with-saga/static/favicon.ico
  examples/with-saga/static/fb-logo.png
  examples/with-saga/static/github-logo.png
  examples/with-saga/static/resolve-logo.png
  examples/with-saga/static/twitter-logo.png
  examples/with-saga/test/functional/index.test.js
  examples/with-saga/test/unit/App.test.js
  packages/resolve-scripts/package.json
  packages/resolve-scripts/src/runtime/server/saga_runner.js
  yarn.lock
Labels: Component: resolve-scripts, Severity: Moderate, Type: Enhancement

#685 Feature/Config template for new app
  examples/hello-world/auth/index.js
  examples/hello-world/client/middlewares/index.js
  examples/hello-world/client/reducers/index.js
  examples/hello-world/client/store/index.js
  examples/hello-world/common/aggregates/default.commands.js
  examples/hello-world/common/aggregates/default.projection.js
  examples/hello-world/common/read-models/default.projection.js
  examples/hello-world/common/read-models/default.resolvers.js
  examples/hello-world/common/sagas/index.js
  examples/hello-world/common/view-models/default.deserialize_state.js
  examples/hello-world/common/view-models/default.projection.js
  examples/hello-world/common/view-models/default.serialize_state.js
  examples/hello-world/resolve.config.json
Labels: Component: Core, Severity: Moderate, Type: Enhancement

#689 Update Contributing.md for nightly builds
  docs/Contributing.md
Labels: Component: Documentation, Severity: Minor, Type: Enhancement
