Repository reimagined/resolve, pull requests merged in 2021-07, with the labels that each got.

#1922 Improve event source mapping (wait for enabled/disabled state)
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/passthrough-error.ts
  packages/runtime/runtime/package.json
  packages/runtime/runtime/src/cloud/init-subscriber.js
  yarn.lock
Labels: enhancement

#1926 Dist subdirectories of examples should not be a part of workspace
  package.json
  yarn.lock
Labels: maintenance

#1925 Middleware support for aggregate commands, read model resolvers and projections
  examples/ts/personal-data/common/aggregates/blog-post.commands.ts
  examples/ts/personal-data/common/aggregates/blog-post.projection.ts
  examples/ts/personal-data/common/aggregates/user-profile.commands.ts
  examples/ts/personal-data/common/middlewares/auth-command-middleware.ts
  examples/ts/personal-data/common/middlewares/auth-resolver-middleware.ts
  examples/ts/personal-data/common/read-models/medias.resolvers.ts
  examples/ts/personal-data/common/read-models/user-profiles.resolvers.ts
  examples/ts/personal-data/config.app.ts
  examples/ts/personal-data/types.ts
  functional-tests/package.json
  packages/core/core/src/aggregate/get-aggregates-interop-builder.ts
  packages/core/core/src/aggregate/types.ts
  packages/core/core/src/helpers.ts
  packages/core/core/src/read-model/get-read-models-interop-builder.ts
  packages/core/core/src/read-model/types.ts
  packages/core/core/src/types/core.ts
  packages/core/core/src/types/runtime.ts
  packages/core/core/test/get-aggregates-interop-builder.unit.test.ts
  packages/core/core/test/get-read-models-interop-builder.unit.test.ts
  packages/runtime/runtime/src/common/command/index.ts
  packages/runtime/runtime/src/common/handlers/command-handler.js
  packages/runtime/runtime/src/common/handlers/query-handler.js
  packages/runtime/runtime/src/common/init-resolve.js
  packages/runtime/runtime/src/common/query/index.ts
  packages/runtime/runtime/src/common/query/wrap-read-model.ts
  packages/runtime/runtime/test/command.test.ts
  packages/tools/scripts/configs/schema.resolve.config.json
  packages/tools/scripts/src/alias/$resolve.middlewares.js
  packages/tools/scripts/src/alias/$resolve.serverAssemblies.js
  packages/tools/scripts/test/__snapshots__/get-webpack-configs.test.js.snap
  packages/tools/scripts/test/alias/__snapshots__/$resolve.serverAssemblies.test.js.snap
  templates/ts/react/client/components/MyAggregateItems.tsx
  templates/ts/react/client/components/MyAggregateList.tsx
  templates/ts/react/common/event-types.ts
  templates/ts/react/common/read-models/my-aggregate-list.projection.ts
  templates/ts/react/static/style.css
  yarn.lock
Labels: feature

#1924 Migrate documentation to docusaurus v2
  .gitignore
  docs/README.md
  docs/advanced-techniques.md
  docs/api-handlers.md
  docs/api-reference.md
  docs/api/api-handler.md
  docs/api/client/entry-point.md
  docs/api/client/http-api.md
  docs/api/client/request-middleware.md
  docs/api/client/resolve-client.md
  docs/api/client/resolve-react-hooks.md
  docs/api/client/resolve-redux.md
  docs/api/event-store-adapter.md
  docs/api/read-model-connector.md
  docs/api/read-model-store.md
  docs/api/resolve-scripts.md
  docs/api/saga.md
  docs/authentication-and-authorization.md
  docs/faq.md
  docs/frontend.md
  docs/read-side.md
  docs/tutorial.md
  docs/write-side.md
  packages/tools/scripts/test/__snapshots__/get-webpack-configs.test.js.snap
  packages/tools/scripts/test/normalize_paths.js
  website/blog/2018-12-5-welcome.md
  website/core/Footer.js
  website/docusaurus.config.js
  website/package.json
  website/pages/en/index.js
  website/sidebars.json
  website/siteConfig.js
  website/src/css/customTheme.css
  website/src/pages/index.js
  website/static/img/favicon.ico
  website/static/img/resolve-light.svg
  website/yarn.lock
Labels: docs

#1927 Collect read model building metrics per event
  functional-tests/app/config.cloud.js
  functional-tests/app/package.json
  package.json
  packages/core/core/src/aggregate/get-aggregates-interop-builder.ts
  packages/core/core/test/get-read-models-interop-builder.unit.test.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/with-performance-tracer.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql-serverless/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
  packages/runtime/runtime/src/cloud/monitoring.js
  packages/runtime/runtime/src/common/query/wrap-read-model.ts
  packages/runtime/runtime/test/cloud/monitoring.test.js
  website/yarn.lock
  yarn.lock
Labels: enhancement

#1930 Fix #1921 and #1928
  examples/ts/hacker-news/client/components/Comment.tsx
  examples/ts/hacker-news/client/containers/NewestByPage.tsx
  examples/ts/hacker-news/client/containers/ShowByPage.tsx
  examples/ts/hacker-news/client/containers/Story.tsx
  examples/ts/hacker-news/client/reducers/optimistic.ts
  examples/ts/hacker-news/package.json
  examples/ts/hacker-news/test/e2e/2.story.ts
  examples/ts/hacker-news/test/e2e/3.comments.ts
Labels: fix

#1929 Implement only one-time event source mapping
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql-serverless/src/passthrough-error.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/__mocks__/pg.js
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/connect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/disconnect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/passthrough-error.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/test/__snapshots__/index.test.ts.snap
  packages/runtime/runtime/src/cloud/init-subscriber.js
  packages/runtime/runtime/test/cloud/init-subscriber.test.js
Labels: enhancement

#1932 Implement monitoring execution counter
  packages/core/core/src/aggregate/get-aggregates-interop-builder.ts
  packages/core/core/src/read-model/get-read-models-interop-builder.ts
  packages/core/core/src/types/runtime.ts
  packages/core/core/src/view-model/get-view-models-interop-builder.ts
  packages/core/core/test/get-aggregates-interop-builder.unit.test.ts
  packages/core/core/test/get-read-models-interop-builder.unit.test.ts
  packages/core/core/test/get-sagas-interop-builder.unit.test.ts
  packages/core/core/test/get-view-models-interop-builder.unit.test.ts
  packages/runtime/runtime/src/cloud/monitoring.js
  packages/runtime/runtime/src/cloud/wrap-api-handler.js
  packages/runtime/runtime/src/common/query/wrap-read-model.ts
  packages/runtime/runtime/src/common/saga/index.js
  packages/runtime/runtime/test/cloud/monitoring.test.js
  packages/tools/testing-tools/src/flow/read-model/make-test-environment.ts
  packages/tools/testing-tools/src/flow/saga/make-test-environment.ts
Labels: enhancement

#1936 Enhance event subscriber prefixes
  packages/runtime/runtime/src/cloud/index.js
  packages/runtime/runtime/src/cloud/init-subscriber.js
  packages/runtime/runtime/src/common/bootstrap.js
  packages/runtime/runtime/src/common/init-resolve.js
  packages/runtime/runtime/src/common/notify-event-subscribers.js
  packages/runtime/runtime/src/common/shutdown.js
  packages/runtime/runtime/src/local/index.js
  packages/runtime/runtime/src/local/reset-domain-handler.js
  packages/runtime/runtime/test/cloud-entry.test.js
Labels: enhancement

#1944 Improve passthrough errors
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/connect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/disconnect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/passthrough-error.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/test/__snapshots__/index.test.ts.snap
  packages/runtime/runtime/src/cloud/init-subscriber.js
Labels: enhancement

#1947 Add injectEvents, run import-export tests on postgres too
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/create-adapter.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/import-events.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/inject-events.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/inject-events.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/inject-events.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/inject-events.ts
  tests/eventstore-test-utils/index.ts
  tests/import-export-sample/import-export.test.ts
Labels: enhancement

#1946 Convert CRA to typescript
  packages/core/create-resolve-app/package.json
  packages/core/create-resolve-app/src/check-application-name.ts
  packages/core/create-resolve-app/src/constants.ts
  packages/core/create-resolve-app/src/create-application.ts
  packages/core/create-resolve-app/src/create-resolve-app.ts
  packages/core/create-resolve-app/src/download-resolve-repo.ts
  packages/core/create-resolve-app/src/format-examples-list.ts
  packages/core/create-resolve-app/src/get-available-examples.ts
  packages/core/create-resolve-app/src/index.ts
  packages/core/create-resolve-app/src/install.ts
  packages/core/create-resolve-app/src/is-yarn-available.ts
  packages/core/create-resolve-app/src/message.ts
  packages/core/create-resolve-app/src/move-example.ts
  packages/core/create-resolve-app/src/patch-package-json.ts
  packages/core/create-resolve-app/src/pipeline.ts
  packages/core/create-resolve-app/src/prepare-options.ts
  packages/core/create-resolve-app/src/print-finish-output.ts
  packages/core/create-resolve-app/src/safe-name.js
  packages/core/create-resolve-app/src/safe-name.ts
  packages/core/create-resolve-app/src/send-analytics.ts
  packages/core/create-resolve-app/test/check-application-name.test.ts
  packages/core/create-resolve-app/test/create-application.test.ts
  packages/core/create-resolve-app/test/download-resolve-repo.test.ts
  packages/core/create-resolve-app/test/install.test.ts
  packages/core/create-resolve-app/test/language-specific-creation.test.ts
  packages/core/create-resolve-app/test/move-example.test.ts
  packages/core/create-resolve-app/test/patch-package-json.test.ts
  packages/core/create-resolve-app/test/safe-name.test.ts
  packages/core/create-resolve-app/test/send-analytics.test.ts
  packages/core/create-resolve-app/tsconfig.json
  packages/core/create-resolve-app/tsconfig.prod.json
  yarn.lock
Labels: maintenance

#1950 Implement toggle notification queue mode
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/connect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/generate-guid.ts
  packages/runtime/runtime/src/cloud/init-subscriber.js
  packages/runtime/runtime/src/cloud/lambda-worker.js
  packages/runtime/runtime/src/common/notify-event-subscribers.js
Labels: enhancement

#1952 Fix replicator pause. Non-parallel replication for postgres. Better error handling
  examples/ts/hacker-news/config.cloud.ts
  examples/ts/hacker-news/config.dev.ts
  packages/modules/module-replication/src/api-handlers/replicate.js
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/create-adapter.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/wrap-method.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/init-replication-state-table.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/replicate-events.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/build.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/call-replicate.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/get-replication-state.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/set-replication-paused.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/types.ts
Labels: enhancement, fix

#1953 Fix config validation warnings on app startup
  packages/tools/scripts/configs/schema.resolve.config.json
  packages/tools/scripts/test/config.test.js
Labels: fix

#1955 Comment out replicator read-model in hacker-news
  examples/ts/hacker-news/config.cloud.ts
  examples/ts/hacker-news/config.dev.ts
Labels: maintenance

#1956 force updated generate-js action run
  examples/js/personal-data/config.app.js
Labels: maintenance

#1957 Passthorugh errors list from monitoring
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/passthrough-error.ts
Labels: enhancement

#1958 Fix extracting http status from error
  packages/runtime/runtime/src/cloud/wrap-api-handler.js
  packages/runtime/runtime/src/common/utils/extract-error-http-code.js
  packages/runtime/runtime/src/common/utils/get-http-status-text.js
  packages/runtime/runtime/test/command-with-custom-error-code.test.ts
  packages/runtime/runtime/test/get-http-status-text.test.ts
Labels: fix

#1960 Fix #1959
  packages/tools/testing-tools/src/flow/read-model/with-adapter.ts
  packages/tools/testing-tools/src/flow/read-model/with-encryption.ts
  packages/tools/testing-tools/test/read-model.test.ts
Labels: fix

#1961 Change default debug level
  .github/workflows/pr-cra.yml
  .github/workflows/pr-dev.yml
  packages/core/debug-levels/src/index.ts
  packages/core/debug-levels/test/index.test.ts
Labels: fix

#1963 Introduce an option for aggregate config that enables or disables returning resulting event to client on command execution.
  examples/ts/personal-data/client/components/PostForm.tsx
  examples/ts/shopping-list/client/components/MyLists.tsx
  examples/ts/shopping-list/client/components/ShoppingListCreator.tsx
  packages/core/core/src/aggregate/get-aggregates-interop-builder.ts
  packages/core/core/src/aggregate/types.ts
  packages/core/core/src/types/core.ts
  packages/core/core/src/types/runtime.ts
  packages/core/core/test/get-aggregates-interop-builder.unit.test.ts
  packages/runtime/runtime/src/common/command/index.ts
  packages/runtime/runtime/src/common/handlers/command-handler.js
  packages/runtime/runtime/test/cloud-entry.test.js
  packages/tools/scripts/configs/schema.resolve.config.json
  packages/tools/scripts/src/alias/$resolve.aggregates.js
  packages/tools/scripts/test/alias/__snapshots__/$resolve.aggregates.test.js.snap
  packages/tools/scripts/test/config.test.js
  templates/js/react/test/unit/aggregates.test.js
  templates/ts/react/client/components/MyAggregateList.tsx
  templates/ts/react/test/unit/aggregates.test.ts
Labels: enhancement

#1967 Fix create-resolve-app incorrect path error on Windows
  internal/cra-test/bin/index.js
  packages/core/create-resolve-app/src/download-resolve-repo.ts
  packages/core/create-resolve-app/src/get-available-examples.ts
  packages/core/create-resolve-app/src/install.ts
  packages/core/create-resolve-app/src/is-yarn-available.ts
  packages/core/create-resolve-app/src/patch-package-json.ts
  packages/core/create-resolve-app/src/print-finish-output.ts
  packages/core/create-resolve-app/src/safe-name.ts
  packages/core/create-resolve-app/src/utils.ts
  packages/core/create-resolve-app/test/get-available-examples.test.ts
  packages/core/create-resolve-app/test/install.test.ts
  packages/core/create-resolve-app/test/safe-name.test.ts
Labels: fix

#1962 useReduxReadModel hook's initial state rendering violation fix
  packages/core/redux/src/internal/action-types.ts
  packages/core/redux/src/read-model/actions.ts
  packages/core/redux/src/read-model/initial-state-manager.ts
  packages/core/redux/src/read-model/read-model-reducer.ts
  packages/core/redux/src/read-model/use-redux-read-model-selector.ts
  packages/core/redux/src/read-model/use-redux-read-model.ts
  packages/core/redux/test/read-model/initial-state-manager.test.ts
  packages/core/redux/test/read-model/read-model-reducer.test.ts
  packages/core/redux/test/read-model/use-redux-read-model-selector.test.ts
  packages/core/redux/test/read-model/use-redux-read-model.test.ts
Labels: bug, fix

#1970 Fix incremental import in sqlite
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/begin-incremental-import.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/commit-incremental-import.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/push-incremental-import.ts
  tests/incremental-import/index.test.js
  tests/package.json
Labels: fix

#1972 Add 'describe' method for eventstore adapater
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/create-adapter.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/describe.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/describe.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/describe.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/describe.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/index.ts
  tests/eventstore-events/index.test.ts
  tests/eventstore-freeze-unfreeze/index.test.ts
  tests/eventstore-secrets/index.test.ts
Labels: feature

#1966 Mention the default logging level
  docs/debugging.md
Labels: docs
