Repository reimagined/resolve, pull requests merged in 2021-12, with the labels that each got.

#2145 Revisit client API docs
  docs/api/client/entry-point.md
  docs/api/client/http-api.md
  docs/api/client/request-middleware.md
  docs/api/client/resolve-client.md
  docs/api/client/resolve-react-hooks.md
  docs/api/client/resolve-redux.md
  docs/frontend.md
Labels: docs

#2162 Core client exports
  packages/core/core/package.json
  packages/core/core/src/browser.ts
Labels: fix

#2161 Fix error monitoring dimensions if name or message is absent
  packages/core/core/src/read-model/get-read-models-interop-builder.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-base/src/index.ts
Labels: fix

#2168 Make more eventstore adapter methods optional
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
Labels: maintenance

#2176 Possible fix saga side effects for #2163
  packages/core/core/src/saga/create-event-handler.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/event-subscriber-notifier-factory.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/lambda-worker.ts
  packages/tools/testing-tools/src/runtime/get-event-store.ts
  packages/tools/testing-tools/test/__snapshots__/read-model.test.ts.snap
Labels: maintenance

#2183 Export events via event loader. Improved export tests
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/export-events.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  tests/import-export-sample/import-export.test.ts
Labels: enhancement

#2184 Use Promise.allSettled in postgres eventstore adapter dispose
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/dispose.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/tsconfig.json
Labels: enhancement

#2186 More detailed command execution monitoring
  packages/core/core/src/aggregate/get-aggregates-interop-builder.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-lite/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
Labels: enhancement

#2181 Update ES Adapter API Reference
  docs/api/event-store-adapter.md
Labels: docs
