Repository reimagined/resolve, pull requests merged in 2021-11, with the labels that each got.

#2099 Fix MDIS
  docs/api/read-model/connector.md
  docs/api/resolve-scripts.md
  docs/api/saga.md
  docs/application-configuration.md
  docs/custom-read-model-connectors.md
  docs/faq.md
  docs/sagas.md
Labels: docs, maintenance

#2098 Fix isAlive in read model status
  .github/workflows/pr-dev.yml
  functional-tests/api/monitoring.test.ts
  functional-tests/app/common/api-handlers/health-check.js
  functional-tests/app/config.app.js
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/status.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/test/status.test.ts
Labels: fix

#2102 Fix postgres event loader closing
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/get-event-loader-native.ts
  tests/node-postgres/index.test.ts
  tests/package.json
Labels: fix

#2104 Don't close connection in event loader if it was terminated
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/get-event-loader-native.ts
  tests/node-postgres/index.test.ts
Labels: fix

#2100 Describe the emulateWorkerLifetimeLimit option
  docs/application-configuration.md
Labels: docs

#2107 Mirror postgresql readmodel.disconnect behavior in eventstore.dispose
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/dispose.ts
Labels: maintenance

#2116 Refactor postgres eventstore error throwing. Fix lint
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/create-adapter.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/save-snapshot.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/set-secret.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/test/connect.unit.test.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/configure.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/connect.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/errors.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/get-event-loader-native.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/make-known-error.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/types.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/build.ts
  tests/eventstore-save-load/index.test.ts
Labels: maintenance

#2115 Fix #1850
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/create-adapter-factory.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/create-adapter.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/wrap-connect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/wrap-is-condition-unsupported-format.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/test/search-condition-unsupported-format.test.ts
  tests/read-model-store-api/find-and-find-one.test.js
Labels: fix

#2121 Better error checks. Print lambda event in top-level event handler
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/connect.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/errors.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/init-replication-state-table.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/lambda-worker.ts
Labels: maintenance

#2117 Fix #1292
  packages/runtime/adapters/monitoring-adapters/monitoring-aws-cloudwatch/package.json
  packages/runtime/adapters/monitoring-adapters/monitoring-aws-cloudwatch/src/__mocks__/aws-sdk/clients/cloudwatch.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-aws-cloudwatch/src/publish.ts
  packages/runtime/runtimes/runtime-aws-serverless/package.json
  packages/runtime/runtimes/runtime-aws-serverless/src/event-subscriber-notifier-factory.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/metrics.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/performance-tracer-factory.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/scheduler-factory.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/send-reactive-event.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/uploader-factory.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/websocket-event-handler.ts
  packages/runtime/runtimes/runtime-base/src/index.ts
  packages/tools/scripts/src/alias/$resolve.backendEntry.js
  yarn.lock
Labels: fix

#2127 Exit process from signal handler. Possible fix for #2126
  packages/runtime/runtimes/runtime-single-process/src/clean-up-process.ts
  packages/tools/scripts/src/process_manager.js
Labels: fix

#2135 Fix bugs
  packages/tools/scripts/src/alias/$resolve.backendEntry.js
  packages/tools/scripts/test/alias/$resolve.backendEntry.test.js
  packages/tools/scripts/test/alias/__snapshots__/$resolve.backendEntry.test.js.snap
Labels: fix

#2139 Detect more errors as ServiceBusyError in postgreql eventstore adapte…
  packages/core/core/src/aggregate/get-aggregates-interop-builder.ts
  packages/modules/module-replication/src/api-handlers/replicated_events.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/errors.ts
Labels: maintenance

#2142 Better logging. Fix #2141. Fix casting loadEventsByTimestamp to JSON
  packages/modules/module-replication/src/api-handlers/replicate.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/load-events-by-timestamp-result.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/throw-bad-cursor.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/load-events-by-timestamp.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/load-events-by-timestamp.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/load-events-by-timestamp.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/build.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/lambda-worker.ts
  packages/tools/scripts/src/process_manager.js
  tests/eventstore-filter-events/index.test.ts
Labels: fix

#2143 Fix api handler path validation
  examples/ts/shopping-list/README.md
  packages/tools/scripts/src/validate_config.js
  packages/tools/scripts/test/config.test.js
  templates/ts/react/run.ts
Labels: fix

#2138 Replace CURL inputs with JS code samples
  docs/api/client/http-api.md
  docs/assets/curl/list1-items.png
  docs/faq.md
  docs/frontend.md
  docs/read-side.md
  docs/write-side.md
Labels: docs

#2144 Add UnrecognizedError and improve postgres eventstore reconnection code
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/errors.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/errors.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
Labels: maintenance

#2148 Remove console monitoring from runtime
  docs/application-configuration.md
  packages/runtime/runtimes/runtime-single-process/package.json
  packages/runtime/runtimes/runtime-single-process/src/index.ts
  packages/runtime/runtimes/runtime-single-process/src/prepare-assemblies.ts
Labels: maintenance

#2153 Remove outdated code and dependencies
  packages/core/client/package.json
  packages/core/redux/package.json
  packages/modules/module-admin/package.json
  packages/modules/module-auth/package.json
  packages/modules/module-auth/test/authenticate_wrapper.test.js
  packages/modules/module-comments/package.json
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/package.json
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/create-query.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/get-latest-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/package.json
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/get-latest-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/get-latest-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/has-events.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/init-replication-state-table.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-lite/package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/package.json
  packages/runtime/adapters/replicators/replicator-via-api-handler/package.json
  packages/tools/scripts/package.json
  packages/tools/testing-tools/package.json
  tests/package.json
  yarn.lock
Labels: maintenance

#2156 Rework replicator-via-api-handler
  examples/ts/hacker-news/config.dev.replica.ts
  examples/ts/hacker-news/config.dev.ts
  packages/core/core/src/types/runtime.ts
  packages/modules/module-replication/package.json
  packages/modules/module-replication/src/api-handlers/get-log.ts
  packages/modules/module-replication/src/api-handlers/occupy_replication.ts
  packages/modules/module-replication/src/api-handlers/pause_replication.ts
  packages/modules/module-replication/src/api-handlers/release_replication.ts
  packages/modules/module-replication/src/api-handlers/replicate.ts
  packages/modules/module-replication/src/api-handlers/replication_state.ts
  packages/modules/module-replication/src/api-handlers/reset_replication.ts
  packages/modules/module-replication/src/api-handlers/respond-with-error.ts
  packages/modules/module-replication/src/api-handlers/resume_replication.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/get-replication-state.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/init-replication-state-table.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/reset-replication.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/set-replication-status.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/get-replication-state.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/init-replication-state-table.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/reset-replication.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/set-replication-status.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/build.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/check-target-url.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/drop-read-model.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/get-replication-state.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/http-error.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/occupy-replication.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/set-replication-paused.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/status.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/types.ts
  tests/eventstore-replication/index.test.ts
Labels: maintenance

#2158 Fix process exit code on error
  packages/tools/scripts/src/process_manager.js
Labels: fix
