Repository reimagined/resolve, pull requests merged in 2021-08, with the labels that each got.

#1976 Module-replication to typescript
  packages/modules/module-replication/package.json
  packages/modules/module-replication/src/api-handlers/pause_replication.ts
  packages/modules/module-replication/src/api-handlers/replicate.ts
  packages/modules/module-replication/src/api-handlers/replicated_events.ts
  packages/modules/module-replication/src/api-handlers/replication_state.ts
  packages/modules/module-replication/src/api-handlers/reset_replication.ts
  packages/modules/module-replication/src/api-handlers/resume_replication.ts
  packages/modules/module-replication/src/index.ts
  packages/modules/module-replication/tsconfig.json
  packages/modules/module-replication/tsconfig.prod.json
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/drop-read-model.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/get-replication-state.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/set-replication-paused.ts
Labels: maintenance

#1979 Improve bootstrapping / Remove some eslint warnings
  examples/ts/hacker-news/config.cloud.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts
  packages/runtime/runtime/src/common/bootstrap-one.js
  packages/runtime/runtime/src/common/bootstrap.js
  packages/runtime/runtime/src/local/start-express.js
Labels: enhancement

#1980 Add test for ConcurrentError. Convert some error types into typescript
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/concurrent-error.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/frozen-errors.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/resource-errors.ts
  tests/eventstore-save-load/index.test.ts
Labels: maintenance

#1982 Implement read model isAlive boolean in status
  .eslintrc.js
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/test/index.test.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-lite/src/status.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-mysql/src/status.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql-serverless/src/status.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/status.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/status.ts
  packages/runtime/runtime/src/common/query/wrap-read-model.ts
Labels: feature

#1984 Fix links to CI and eventstore adapters directories
  README.md
  docs/write-side.md
Labels: docs

#1985 Review READMEs for event store adapters
  packages/runtime/adapters/eventstore-adapters/README.md
  packages/runtime/adapters/eventstore-adapters/eventstore-base/README.md
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/README.md
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/README.md
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/README.md
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/README.md
Labels: docs

#1983 Fix broken links and structural inconsistencies
  docs/README.md
  docs/introduction.md
  website/docusaurus.config.js
  website/sidebars.json
  website/src/pages/index.js
Labels: docs, maintenance

#1990 Better error message for failed read-model in PLV8
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
Labels: enhancement

#1986 Split the "Advanced Techniques" topic into separate documents for easier navigation
  docs/README.md
  docs/adapters.md
  docs/advanced-techniques.md
  docs/authentication-and-authorization.md
  docs/code-splitting.md
  docs/custom-read-model-connectors.md
  docs/encryption.md
  docs/export-import.md
  docs/file-upload.md
  docs/modules.md
  docs/preparing-to-production.md
  docs/write-side.md
  website/sidebars.json
Labels: docs

#1977 Add short descriptions to API docs
  docs/api/api-handler.md
  docs/api/client/entry-point.md
  docs/api/client/http-api.md
  docs/api/client/request-middleware.md
  docs/api/client/resolve-client.md
  docs/api/client/resolve-react-hooks.md
  docs/api/client/resolve-redux.md
  docs/api/event-store-adapter.md
  docs/api/read-model-connector.md
  docs/api/read-model-store.md
  docs/api/resolve-scripts.md
  docs/api/saga.md
  docs/troubleshooting.md
Labels: docs

#1995 Fix #1994
  .github/workflows/pr-dev.yml
  packages/core/core/src/aggregate/get-aggregates-interop-builder.ts
  packages/core/core/test/get-aggregates-interop-builder.unit.test.ts
  packages/runtime/runtime/test/cloud-entry.test.js
  packages/tools/scripts/src/write_package_jsons_for_assemblies.js
Labels: fix

#2000 Force the workflow "push-to-dev"
  tests/eventstore-test-utils/index.ts
Labels: maintenance

#1993 Review READMEs for read model adapters
  packages/runtime/adapters/readmodel-adapters/readmodel-base/README.md
  packages/runtime/adapters/readmodel-adapters/readmodel-lite/README.md
  packages/runtime/adapters/readmodel-adapters/readmodel-mysql/README.md
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql-serverless/README.md
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/README.md
Labels: docs, maintenance

#2003 Add tests for getLatestEvent
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/get-latest-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/get-latest-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/get-latest-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/get-latest-event.ts
  tests/eventstore-events/index.test.ts
Labels: enhancement, maintenance

#2006 Revert read-model-store-api/upsert.test.js
  tests/read-model-store-api/upsert.test.js
Labels: maintenance

#1996 Add intro to the root topic
  docs/introduction.md
Labels: docs

#2018 Add missing types dependencies
  examples/ts/hacker-news/package.json
  yarn.lock
Labels: maintenance

#2020 Add missing type dependencies
  examples/ts/hacker-news/package.json
  yarn.lock
Labels: maintenance

#2021 Increase release reviews quorum to 4
  .github/workflows/pr-release.yml
Labels: maintenance

#2022 Add missing type dependencies
  templates/ts/postcss/package.json
  yarn.lock
Labels: maintenance

#2023 Restore changelog generation
  .github/workflows/push-dev.yml
  .github/workflows/push-master.yml
  HISTORY.md
Labels: fix

#2019 Release 0.31.9
  .eslintrc.js
  .github/workflows/pr-release.yml
  .github/workflows/push-dev.yml
  .github/workflows/push-master.yml
  CHANGELOG.md
  HISTORY.md
  examples/ts/hacker-news/package.json
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/describe.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/describe.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/describe.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/tools/scripts/package.json
  packages/tools/scripts/src/write_package_jsons_for_assemblies.js
  templates/ts/postcss/package.json
  tests/eventstore-events/index.test.ts
  tests/eventstore-save-load/index.test.ts
  tests/read-model-store-api/count.test.js
  yarn.lock
Labels: release
