Repository reimagined/resolve, pull requests merged in 2021-09, with the labels that each got.

#2004 Describe middleware
  docs/api/command-handler.md
  docs/api/middleware.md
  docs/api/read-model-event-handler.md
  docs/api/read-model-resolver.md
  docs/application-configuration.md
  docs/middleware.md
  website/sidebars.json
Labels: docs

#2025 Fix unstable test for incremental import
  tests/incremental-import/index.test.js
Labels: maintenance

#2028 More elaborate tests for eventstore adapters
  .eslintrc.js
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/incremental-import.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/push-incremental-import.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/push-incremental-import.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/push-incremental-import.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/push-incremental-import.ts
  tests/eventstore-events/index.test.ts
  tests/eventstore-parallel-save/index.test.ts
  tests/eventstore-save-load/index.test.ts
  tests/eventstore-secrets/index.test.ts
  tests/eventstore-test-utils/index.ts
  tests/import-export-sample/import-export.test.ts
  tests/incremental-import/create-adapter.ts
  tests/incremental-import/index.test.ts
Labels: maintenance

#2029 Fix grammar in the introduction
  docs/introduction.md
Labels: docs, maintenance

#2001 Describe the store.find projection argument
  docs/api/read-model-store.md
Labels: docs

#2031 Speedup events export and export tests
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/export-events.ts
  tests/eventstore-test-utils/index.ts
  tests/import-export-sample/import-export.test.ts
Labels: enhancement

#2034 Update minimal node version to 14
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/manual-cloud-test.yml
  .github/workflows/pr-cra.yml
  .github/workflows/pr-dev.yml
  .github/workflows/push-master.yml
  README.md
  docs/introduction.md
  examples/ts/hacker-news/package.json
  examples/ts/personal-data/package.json
  examples/ts/shopping-list-redux-hoc/package.json
  examples/ts/shopping-list-redux/package.json
  examples/ts/shopping-list/package.json
  internal/helpers/get-babel-config.js
  package.json
  packages/core/client/package.json
  packages/core/core/package.json
  packages/core/create-resolve-app/package.json
  packages/core/create-resolve-app/test/download-resolve-repo.test.ts
  packages/core/debug-levels/package.json
  packages/core/react-hooks/package.json
  packages/core/redux/package.json
  packages/modules/module-admin/package.json
  packages/modules/module-auth/package.json
  packages/modules/module-comments/package.json
  packages/modules/module-replication/package.json
  packages/modules/module-uploader/package.json
  packages/runtime/adapters/eventstore-adapters/eventstore-base/package.json
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/package.json
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/package.json
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/package.json
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-base/package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-lite/package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-mysql/package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql-serverless/package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/package.json
  packages/runtime/adapters/replicators/replicator-via-api-handler/package.json
  packages/runtime/runtime/package.json
  packages/tools/scripts/package.json
  packages/tools/scripts/src/get_webpack_common_configs.js
  packages/tools/scripts/test/__snapshots__/get-webpack-configs.test.js.snap
  packages/tools/testing-tools/package.json
  templates/ts/angular/package.json
  templates/ts/react/package.json
  tests/custom-readmodel-sample/connector.js
  yarn.lock
Labels: breaking

#2036 Fix eventSubscribers notify timeout / Add "soft" flag to shutdown
  packages/runtime/runtime/package.json
  packages/runtime/runtime/src/cloud/deploy-service-event-handler.js
  packages/runtime/runtime/src/common/notify-event-subscribers.js
  packages/runtime/runtime/src/common/query/wrap-read-model.ts
  packages/runtime/runtime/src/common/shutdown.js
  yarn.lock
Labels: fix

#2012 Remove redundant code
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/coercer.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/connect.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/test/connect.unit.test.ts
  packages/runtime/runtime/src/cloud/websocket-event-handler.js
  packages/runtime/runtime/src/common/init-resolve.js
Labels: maintenance

#2039 Fix #1994
  packages/core/core/src/aggregate/get-aggregates-interop-builder.ts
  packages/core/core/test/get-aggregates-interop-builder.unit.test.ts
Labels: fix

#2041 Fix #2024
  packages/runtime/runtime/src/local/index.js
  packages/runtime/runtime/src/local/init-uploader.js
  packages/runtime/runtime/src/local/start-express.js
  packages/tools/scripts/configs/schema.resolve.config.json
  packages/tools/scripts/src/alias/$resolve.constants.js
  packages/tools/scripts/src/alias/$resolve.host.js
  packages/tools/scripts/src/open_browser.js
  packages/tools/scripts/src/watch_mode.js
  packages/tools/scripts/test/__snapshots__/get-webpack-configs.test.js.snap
  packages/tools/scripts/test/alias/$resolve.host.test.js
  packages/tools/scripts/test/alias/__snapshots__/$resolve.constants.test.js.snap
  packages/tools/scripts/test/alias/__snapshots__/$resolve.host.test.js.snap
Labels: fix

#2042 Improvements
  .eslintrc.js
  .gitignore
  .prettierignore
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/connect.ts
  tests/import-export-sample/import-export.test.ts
  tutorial/lesson-1/config.test-functional.js
  tutorial/lesson-1/package.json
  tutorial/lesson-1/run.js
  tutorial/lesson-1/test/e2e/index.test.js
  tutorial/lesson-1/yarn.lock
  tutorial/lesson-2/config.test-functional.js
  tutorial/lesson-2/package.json
  tutorial/lesson-2/run.js
  tutorial/lesson-2/test/e2e/index.test.js
  tutorial/lesson-2/yarn.lock
  tutorial/lesson-3/config.test-functional.js
  tutorial/lesson-3/package.json
  tutorial/lesson-3/run.js
  tutorial/lesson-3/test/e2e/index.test.js
  tutorial/lesson-3/yarn.lock
  tutorial/lesson-4/config.test-functional.js
  tutorial/lesson-4/package.json
  tutorial/lesson-4/run.js
  tutorial/lesson-4/test/e2e/index.test.js
  tutorial/lesson-4/yarn.lock
  tutorial/lesson-5/config.test-functional.js
  tutorial/lesson-5/package.json
  tutorial/lesson-5/run.js
  tutorial/lesson-5/test/e2e/index.test.js
  tutorial/lesson-5/yarn.lock
  yarn.lock
Labels: maintenance

#2043 Describe the `host` option
  docs/application-configuration.md
Labels: docs

#2038 Fix header button adaptivity
  website/src/css/customTheme.css
Labels: docs, maintenance

#2046 Use consistent favicons between sites
  website/docusaurus.config.js
  website/static/img/favicon.ico
  website/static/img/favicon.png
Labels: docs, maintenance

#2049 Fix storing of read model projection errors if plv8 is used
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
Labels: fix

#2048 Fix send notifications for event subscribers in cloud runtime
  packages/runtime/runtime/package.json
  packages/runtime/runtime/src/cloud/init-subscriber.js
  yarn.lock
Labels: fix

#2047 Ignore already disposed error on loadEvents in readmodel build
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/errors.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/wrap-dispose.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/wrap-method.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
Labels: fix

#2051 Fix #2044
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/inline-ledger-force-stop.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/test/inline-ledger-force-stop.test.ts
Labels: fix
