Repository reimagined/resolve, pull requests merged in 2021-06, with the labels that each got.

#1887 Fix #1886 - parallel write in sqlite eventstore adapter
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/delete-secret.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/save-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/set-secret.ts
  tests/eventstore-parallel-save/index.test.ts
  tests/package.json
Labels: fix

#1888 Add manual workflow for cloud test
  .github/workflows/manual-cloud-test.yml
Labels: maintenance

#1890 Fix #1874
  functional-tests/app/client/redux-hooks/components/CustomAggregateIds.js
  functional-tests/app/client/redux-hooks/routes.js
  functional-tests/app/common/view-models/custom-aggregate-ids.projection.js
  functional-tests/app/common/view-models/custom-aggregate-ids.resolver.js
  functional-tests/app/config.app.js
  functional-tests/testcafe/redux-hooks/custom-aggregate-ids.test.ts
  packages/core/client/src/client.ts
  packages/core/core/src/view-model/types.ts
  packages/core/react-hooks/src/use-view-model.ts
  packages/core/react-hooks/test/use-view-model.unit.test.tsx
Labels: fix

#1889 Fix #1883
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/cursor-operations.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/load-events-by-cursor.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/load-events-by-cursor.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/load-events-by-cursor.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql-serverless/src/passthrough-error.ts
  tests/eventstore-events/index.test.ts
  tests/package.json
Labels: fix

#1891 Fix duplicated events in view-model subscriptions
  packages/core/client/package.json
  packages/core/client/src/subscribe-adapter.ts
  packages/core/client/test/unit/subscription-adapter.unit.test.ts
  packages/runtime/runtime/src/cloud/index.js
  packages/runtime/runtime/src/cloud/websocket-event-handler.js
  packages/runtime/runtime/src/local/create-pubsub-manager.js
  packages/runtime/runtime/src/local/init-websockets.js
  yarn.lock
Labels: fix

#1892 Add checkEventsContinuity
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/cursor-operations.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/delete-secret.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/replicate-events.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/save-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/save-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/save-event.ts
  tests/eventstore-save-load/index.test.ts
Labels: maintenance

#1895 Change outdated travis badge to github actions one, update nodejs version in README
  README.md
Labels: docs, maintenance

#1898 Implement inline projection execution in RDBMS PostgreSQL via PLV8 extenstion
  .eslintrc.js
  .github/workflows/pr-dev.yml
  package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/index.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql-serverless/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql-serverless/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/connect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/count.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/define-table.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/delete.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/find-one.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/find.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/index.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/insert.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/make-nested-path.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/make-sql-query.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/passthrough-error.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/resubscribe.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/subscribe.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/unsubscribe.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/update.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/wrap-procedure.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/test/__snapshots__/index.test.ts.snap
  packages/runtime/runtime/src/common/init-resolve.js
  packages/runtime/runtime/src/common/query/types.ts
  packages/runtime/runtime/src/common/query/wrap-read-model.ts
  packages/runtime/runtime/src/common/utils/live-entry-dir.js
  packages/runtime/runtime/src/common/utils/live-require.js
  packages/runtime/runtime/src/common/utils/pure-require.js
  packages/runtime/runtime/test/cloud-entry.test.js
  packages/tools/scripts/package.json
  packages/tools/scripts/src/alias/$resolve.readModel.js
  packages/tools/scripts/src/alias/$resolve.readModelProcedure.js
  packages/tools/scripts/src/alias/$resolve.readModels.js
  packages/tools/scripts/src/build_mode.js
  packages/tools/scripts/src/constants.js
  packages/tools/scripts/src/detect_errors.js
  packages/tools/scripts/src/generate_custom_mode.js
  packages/tools/scripts/src/get_webpack_client_configs.js
  packages/tools/scripts/src/get_webpack_common_configs.js
  packages/tools/scripts/src/show_build_info.js
  packages/tools/scripts/src/watch_mode.js
  packages/tools/scripts/test/__snapshots__/get-webpack-configs.test.js.snap
  packages/tools/scripts/test/alias/__snapshots__/$resolve.readModels.test.js.snap
  yarn.lock
Labels: feature

#1904 Fix #1903, add tests
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/create-query.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/constants.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/load-events-by-cursor.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/load-events-by-timestamp.ts
  tests/eventstore-events/index.test.ts
  tests/eventstore-test-utils/index.ts
Labels: fix

#1906 Fix sqlite saveEvent
  examples/ts/hacker-news/config.dev.replica.ts
  examples/ts/hacker-news/config.prod.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/save-event.ts
  tests/eventstore-parallel-save/index.test.ts
  tests/eventstore-save-load/index.test.ts
Labels: fix

#1905 Add SQS integration
  .eslintrc.js
  .github/workflows/pr-dev.yml
  packages/core/core/src/aggregate/get-aggregates-interop-builder.ts
  packages/core/core/src/aggregate/types.ts
  packages/core/core/src/types/runtime.ts
  packages/core/create-resolve-app/test/download-resolve-repo.test.js
  packages/runtime/runtime/package.json
  packages/runtime/runtime/src/cloud/deploy-service-event-handler.js
  packages/runtime/runtime/src/cloud/index.js
  packages/runtime/runtime/src/cloud/init-aws-clients.js
  packages/runtime/runtime/src/cloud/init-subscriber.js
  packages/runtime/runtime/src/cloud/lambda-worker.js
  packages/runtime/runtime/src/common/bootstrap-one.js
  packages/runtime/runtime/src/common/bootstrap.js
  packages/runtime/runtime/src/common/init-resolve.js
  packages/runtime/runtime/src/common/notify-event-subscribers.js
  packages/runtime/runtime/src/common/on-command-executed.js
  packages/runtime/runtime/src/common/query/types.ts
  packages/runtime/runtime/src/common/query/wrap-read-model.ts
  packages/runtime/runtime/src/common/saga/index.js
  packages/runtime/runtime/src/common/shutdown-one.js
  packages/runtime/runtime/src/common/shutdown.js
  packages/runtime/runtime/src/local/index.js
  packages/runtime/runtime/test/cloud-entry.test.js
  packages/runtime/runtime/test/query.test.ts
  packages/runtime/runtime/test/wrap-read-model.test.ts
  packages/tools/testing-tools/src/flow/read-model/make-test-environment.ts
  packages/tools/testing-tools/src/flow/saga/make-test-environment.ts
  yarn.lock
Labels: feature

#1908 Restore PLV8
  packages/tools/scripts/package.json
  packages/tools/scripts/src/alias/$resolve.readModel.js
  packages/tools/scripts/src/alias/$resolve.readModelProcedure.js
  yarn.lock
Labels: fix

#1909 Don't create new instance of postgres connection per each query
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/connect.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/dispose.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/types.ts
Labels: enhancement

#1911 Fix: url not a constructor
  examples/ts/hacker-news/client/containers/Story.tsx
  examples/ts/hacker-news/test/e2e/2.story.ts
Labels: fix

#1912 More checks for cursor operations
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/cursor-operations.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql-serverless/src/save-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/save-event.ts
Labels: maintenance

#1914 Fix SQS prefixes and eventstore-base TS types exports
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/index.ts
  packages/runtime/runtime/src/cloud/init-subscriber.js
Labels: maintenance

#1919 Remove outdated replicator code
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/.npmignore
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/README.md
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/package.json
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/__mocks__/aws-sdk/clients/rdsdataservice.js
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/build.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/coercer.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/connect.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/drop-read-model.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/escape-id.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/escape-str.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/index.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/is-highload-error.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/pause.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/raw-execute-statement.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/reset.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/resubscribe.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/resume.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/status.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/types.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/src/unsubscribe.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/test/index.test.ts
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/tsconfig.json
  packages/runtime/adapters/replicators/replicator-postgresql-serverless/tsconfig.prod.json
Labels: maintenance

#1918 Restructure the documentation to account for moved examples
  docs/advanced-techniques.md
  docs/api-reference.md
  docs/authentication-and-authorization.md
  docs/frontend.md
  docs/introduction.md
  docs/preparing-to-production.md
  docs/read-side.md
  docs/tutorial.md
  docs/write-side.md
  examples/README.md
  examples/ts/shopping-list-redux-hoc/README.md
  examples/ts/shopping-list-redux/README.md
  packages/core/create-resolve-app/README.md
  templates/README.md
  templates/ts/angular/README.md
  templates/ts/postcss/README.md
  templates/ts/react/README.md
  templates/ts/styled-components/README.md
  templates/ts/vanilla/README.md
  templates/ts/vue/README.md
Labels: docs

#1920 Improve tests to handle possible errors on big number of events.
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/get-cursor-until-event-types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/replicate-events.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/save-event.ts
  tests/eventstore-replication/index.test.ts
  tests/eventstore-save-load/index.test.ts
  yarn.lock
Labels: maintenance
