Repository reimagined/resolve, pull requests merged in 2022-03, with the labels that each got.

#2248 One direction next invocation / refactor runtime-base
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/test/index.test.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-lite/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-lite/src/resume.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-mysql/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-mysql/src/resume.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/resume.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/build.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/resume.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/lambda-worker.ts
  packages/runtime/runtimes/runtime-aws-serverless/test/wrap-api-handler.unit.test.ts
  packages/runtime/runtimes/runtime-base/src/bootstrap-one.ts
  packages/runtime/runtimes/runtime-base/src/command.ts
  packages/runtime/runtimes/runtime-base/src/create-runtime.ts
  packages/runtime/runtimes/runtime-base/src/custom-read-model.ts
  packages/runtime/runtimes/runtime-base/src/event-subscriber.ts
  packages/runtime/runtimes/runtime-base/src/event-subscribers-lifecycle.ts
  packages/runtime/runtimes/runtime-base/src/event-subscribers-properties.ts
  packages/runtime/runtimes/runtime-base/src/handlers/command-handler.ts
  packages/runtime/runtimes/runtime-base/src/handlers/query-handler.ts
  packages/runtime/runtimes/runtime-base/src/index.ts
  packages/runtime/runtimes/runtime-base/src/notification-next.ts
  packages/runtime/runtimes/runtime-base/src/parse-event-subscriber-parameters.ts
  packages/runtime/runtimes/runtime-base/src/query.ts
  packages/runtime/runtimes/runtime-base/src/query/batch.ts
  packages/runtime/runtimes/runtime-base/src/query/get-log.ts
  packages/runtime/runtimes/runtime-base/src/query/index.ts
  packages/runtime/runtimes/runtime-base/src/query/parse-read-options.ts
  packages/runtime/runtimes/runtime-base/src/query/types.ts
  packages/runtime/runtimes/runtime-base/src/query/wrap-read-model.ts
  packages/runtime/runtimes/runtime-base/src/query/wrap-view-model.ts
  packages/runtime/runtimes/runtime-base/src/saga/__mocks__/uuid/v4.js
  packages/runtime/runtimes/runtime-base/src/saga/get-log.ts
  packages/runtime/runtimes/runtime-base/src/saga/index.ts
  packages/runtime/runtimes/runtime-base/src/side-effect-timestamp-provider.ts
  packages/runtime/runtimes/runtime-base/src/types.ts
  packages/runtime/runtimes/runtime-single-process/src/prepare-domain.ts
  packages/runtime/runtimes/runtime-single-process/test/wrap-api-handler.unit.test.ts
  packages/tools/testing-tools/src/flow/read-model/make-test-environment.ts
  packages/tools/testing-tools/src/flow/saga/make-test-environment.ts
Labels: maintenance

#2249 Implement support for PLV8 ver 3.1
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/wrap-procedure.ts
Labels: enhancement

#2250 Fix eliminated error message in Init projection handler
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
  tests/read-model-store-api/projection-fail-init.test.js
Labels: bug

#2252 Update README.md
  README.md
Labels: maintenance

#2255 Use mdis code sampes in the Running in Containers guide
  docs/running-in-containers.md
Labels: docs, maintenance

#2256 Review module READMEs
  packages/modules/module-auth/README.md
  packages/modules/module-comments/README.md
Labels: docs, maintenance

#2254 Add encryption API reference
  docs/api/encryption/factory-function.md
  docs/api/encryption/secrets-manager.md
  docs/encryption.md
  website/sidebars.json
Labels: docs

#2260 Remove React Native mention from README
  README.md
Labels: docs, maintenance

#2259 Fix Github Actions workflows
  .github/workflows/manual-cloud-test.yml
  .github/workflows/pr-dev.yml
  functional-tests/api/benchmark.test.ts
  packages/core/core/test/get-aggregates-interop-builder.unit.test.ts
  packages/core/core/test/get-read-models-interop-builder.unit.test.ts
  packages/core/core/test/get-view-models-interop-builder.unit.test.ts
  packages/core/redux/src/view-model/event-listener-saga.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/bind-method.ts
Labels: maintenance
