Repository reimagined/resolve, pull requests merged in 2022-01, with the labels that each got.

#2188 Bump compilerOptions.target to "es2020" (for only-server packages)
  packages/core/create-resolve-app/tsconfig.json
  packages/modules/module-replication/tsconfig.json
  packages/runtime/adapters/eventstore-adapters/eventstore-base/tsconfig.json
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/tsconfig.json
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/tsconfig.json
  packages/runtime/adapters/monitoring-adapters/monitoring-aws-cloudwatch/tsconfig.json
  packages/runtime/adapters/monitoring-adapters/monitoring-base/tsconfig.json
  packages/runtime/adapters/monitoring-adapters/monitoring-console/tsconfig.json
  packages/runtime/adapters/readmodel-adapters/readmodel-base/tsconfig.json
  packages/runtime/adapters/readmodel-adapters/readmodel-lite/tsconfig.json
  packages/runtime/adapters/readmodel-adapters/readmodel-mysql/tsconfig.json
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/tsconfig.json
  packages/runtime/adapters/replicators/replicator-via-api-handler/tsconfig.json
  packages/runtime/runtimes/runtime-aws-serverless/tsconfig.json
  packages/runtime/runtimes/runtime-base/tsconfig.json
  packages/runtime/runtimes/runtime-single-process/tsconfig.json
  packages/tools/testing-tools/tsconfig.json
Labels: maintenance

#2190 Fix log names
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/get-log.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/get-log.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/get-log.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/get-log.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/get-log.ts
Labels: fix

#2191 Add custom monitoring method. Add metric for reconnection times in postgresql eventstore adapter
  .eslintrc.js
  packages/core/core/src/types/runtime.ts
  packages/core/core/test/get-aggregates-interop-builder.unit.test.ts
  packages/core/core/test/get-read-models-interop-builder.unit.test.ts
  packages/core/core/test/get-sagas-interop-builder.unit.test.ts
  packages/core/core/test/get-view-models-interop-builder.unit.test.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/create-adapter.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/dispose.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-aws-cloudwatch/src/index.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-base/src/index.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-base/test/index.test.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-console/src/index.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-console/test/index.test.ts
  packages/runtime/runtimes/runtime-aws-serverless/test/index.test.ts
  packages/runtime/runtimes/runtime-base/src/create-composite-monitoring-adapter.ts
  packages/runtime/runtimes/runtime-base/src/create-runtime.ts
  packages/tools/testing-tools/src/flow/read-model/make-test-environment.ts
  packages/tools/testing-tools/src/flow/saga/make-test-environment.ts
  tests/eventstore-connect-dispose/index.test.ts
  tests/package.json
Labels: enhancement

#2187 Filter event subscriber notifications
  packages/runtime/runtimes/runtime-base/src/event-broadcast-factory.ts
  packages/runtime/runtimes/runtime-base/src/query/wrap-read-model.ts
  packages/runtime/runtimes/runtime-base/test/event-broadcast-factory.test.ts
Labels: maintenance

#2194 Improve jitter in readmodel-postgres adapter
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-mysql/tsconfig.json
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/connect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/disconnect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/test/__snapshots__/index.test.ts.snap
  tests/package.json
  tests/read-model-builder-postgres/index.test.ts
  tests/readmodel-test-utils/index.ts
Labels: enhancement

#2195 Release 0.33.9
  .eslintrc.js
  .github/workflows/pr-dev.yml
  CHANGELOG.md
  docs/api/event-store-adapter.md
  package.json
  packages/core/core/src/types/runtime.ts
  packages/core/core/test/get-aggregates-interop-builder.unit.test.ts
  packages/core/core/test/get-read-models-interop-builder.unit.test.ts
  packages/core/core/test/get-sagas-interop-builder.unit.test.ts
  packages/core/core/test/get-view-models-interop-builder.unit.test.ts
  packages/core/create-resolve-app/tsconfig.json
  packages/modules/module-replication/tsconfig.json
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/create-adapter.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/get-log.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/src/types.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-base/tsconfig.json
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/src/get-log.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-lite/tsconfig.json
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/src/get-log.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-mysql/tsconfig.json
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/dispose.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/execute-statement.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/get-log.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-aws-cloudwatch/src/index.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-aws-cloudwatch/tsconfig.json
  packages/runtime/adapters/monitoring-adapters/monitoring-base/src/index.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-base/test/index.test.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-base/tsconfig.json
  packages/runtime/adapters/monitoring-adapters/monitoring-console/src/index.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-console/test/index.test.ts
  packages/runtime/adapters/monitoring-adapters/monitoring-console/tsconfig.json
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-base/tsconfig.json
  packages/runtime/adapters/readmodel-adapters/readmodel-lite/tsconfig.json
  packages/runtime/adapters/readmodel-adapters/readmodel-mysql/tsconfig.json
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/build.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/connect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/disconnect.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/get-log.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/test/__snapshots__/index.test.ts.snap
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/tsconfig.json
  packages/runtime/adapters/replicators/replicator-via-api-handler/tsconfig.json
  packages/runtime/runtimes/runtime-aws-serverless/test/index.test.ts
  packages/runtime/runtimes/runtime-aws-serverless/tsconfig.json
  packages/runtime/runtimes/runtime-base/src/create-composite-monitoring-adapter.ts
  packages/runtime/runtimes/runtime-base/src/create-runtime.ts
  packages/runtime/runtimes/runtime-base/src/event-broadcast-factory.ts
  packages/runtime/runtimes/runtime-base/src/handlers/command-handler.ts
  packages/runtime/runtimes/runtime-base/src/query/wrap-read-model.ts
  packages/runtime/runtimes/runtime-base/test/event-broadcast-factory.test.ts
  packages/runtime/runtimes/runtime-base/tsconfig.json
  packages/runtime/runtimes/runtime-single-process/tsconfig.json
  packages/tools/testing-tools/src/flow/read-model/make-test-environment.ts
  packages/tools/testing-tools/src/flow/saga/make-test-environment.ts
  packages/tools/testing-tools/tsconfig.json
  tests/eventstore-connect-dispose/index.test.ts
  tests/package.json
  tests/read-model-builder-postgres/index.test.ts
  tests/readmodel-test-utils/index.ts
  yarn.lock
Labels: release

#2196 Optimize loadevents for postgresql eventstore adapter
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/create-load-query.ts
Labels: enhancement

#2197 Rename the "Preparing to Production" article to "Preparing for Production"
  docs/README.md
  docs/preparing-for-production.md
  docs/tutorial.md
  website/sidebars.json
Labels: docs, maintenance

#2212 Benchmarks for postgresql eventstore loadEvents and saveEvent
  benchmarks/.eslintrc.js
  benchmarks/.gitignore
  benchmarks/README.md
  benchmarks/eventstore/event-spec.example.json
  benchmarks/eventstore/import-eventstore.ts
  benchmarks/eventstore/load-events.ts
  benchmarks/eventstore/save-event.ts
  benchmarks/eventstore/utils.ts
  benchmarks/package.json
  benchmarks/tsconfig.json
  package.json
  yarn.lock
Labels: feature

#2213 Implement is alive timeout
  packages/runtime/adapters/readmodel-adapters/readmodel-base/src/types.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-lite/src/status.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-mysql/src/status.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/status.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/test/status.test.ts
  packages/runtime/adapters/replicators/replicator-via-api-handler/src/status.ts
  packages/runtime/runtimes/runtime-base/src/create-runtime.ts
  packages/runtime/runtimes/runtime-base/src/event-broadcast-factory.ts
  packages/runtime/runtimes/runtime-base/src/query/wrap-read-model.ts
  packages/runtime/runtimes/runtime-base/test/event-broadcast-factory.test.ts
Labels: maintenance

#2216 Optimize event loading by single aggregateId (special case)
  benchmarks/eventstore/save-event.ts
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/create-load-query.ts
  tests/eventstore-filter-events/index.test.ts
Labels: enhancement

#2218 Fix security issues
  examples/js/hacker-news/package.json
  examples/ts/hacker-news/package.json
  functional-tests/package.json
  packages/core/client/package.json
  packages/runtime/adapters/eventstore-adapters/eventstore-base/package.json
  packages/runtime/adapters/replicators/replicator-via-api-handler/package.json
  packages/runtime/runtimes/runtime-aws-serverless/package.json
  packages/runtime/runtimes/runtime-single-process/package.json
  yarn.lock
Labels: maintenance

#2220 Fullfill postgresql passthrough errors
  packages/runtime/adapters/eventstore-adapters/eventstore-postgresql/src/errors.ts
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/passthrough-error.ts
Labels: enhancement, maintenance
