Repository reimagined/resolve, pull requests merged in 2022-04, with the labels that each got.

#2247 Add info about TypeScript support
  docs/api/aggregate/command-handler.md
  docs/api/aggregate/projection.md
  docs/api/api-handler/api-handler.md
  docs/api/api-handler/resolve-context.md
  docs/api/command.md
  docs/api/event.md
  docs/api/middleware.md
  docs/api/monitoring/metric.md
  docs/api/monitoring/monitoring-adapter.md
  docs/api/monitoring/monitoring.md
  docs/api/read-model/projection.md
  docs/api/read-model/query.md
  docs/api/read-model/resolver.md
  docs/api/read-model/store.md
  docs/api/saga.md
  docs/api/view-model/projection.md
  docs/api/view-model/query.md
  docs/api/view-model/resolver.md
  docs/typescript-support.md
  website/sidebars.json
Labels: docs

#2262 Skip CI self-hosted runner. Fix security issues
  .github/workflows/push-dev.yml
  benchmarks/package.json
  internal/babel-compile/package.json
  internal/cra-test/package.json
  internal/helpers/package.json
  internal/use-local-registry/package.json
  internal/workspaces/package.json
  yarn.lock
Labels: maintenance

#2265 Update the api/view-model/query article
  docs/api/view-model/query.md
Labels: docs, maintenance

#2266 Improve post save event notification performance
  packages/runtime/runtimes/runtime-aws-serverless/src/send-reactive-event.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/websocket-event-handler.ts
Labels: enhancement

#2267 Release 0.34.1
  CHANGELOG.md
  docs/api/view-model/query.md
  examples/js/hacker-news/config.cloud.common.js
  examples/js/personal-data/config.cloud.js
  examples/js/shopping-list-redux-hoc/config.cloud.js
  examples/js/shopping-list-redux/config.cloud.js
  examples/js/shopping-list/config.cloud.js
  examples/ts/hacker-news/config.cloud.common.ts
  examples/ts/personal-data/config.cloud.ts
  examples/ts/shopping-list-redux-hoc/config.cloud.ts
  examples/ts/shopping-list-redux/config.cloud.ts
  examples/ts/shopping-list/config.cloud.ts
  functional-tests/app/common/read-models/saga-tests.projection.js
  functional-tests/app/common/read-models/test-scenarios.projection.js
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/package.json
  packages/runtime/adapters/readmodel-adapters/readmodel-postgresql/src/wrap-procedure.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/send-reactive-event.ts
  packages/runtime/runtimes/runtime-aws-serverless/src/websocket-event-handler.ts
Labels: release

#2269 Improve post command performance to decrease response time
  packages/runtime/runtimes/runtime-aws-serverless/src/send-reactive-event.ts
  packages/runtime/runtimes/runtime-base/src/command-executed-hook-factory.ts
Labels: fix

#2270 Release 0.34.2
  packages/runtime/runtimes/runtime-aws-serverless/src/send-reactive-event.ts
  packages/runtime/runtimes/runtime-base/src/command-executed-hook-factory.ts
Labels: release

#2271 Bad grammar in the fail handler error message
  packages/runtime/runtimes/runtime-aws-serverless/test/index.test.ts
  packages/runtime/runtimes/runtime-base/src/handlers/fail-handler.ts
Labels: maintenance

#2272 Update copyright
  website/docusaurus.config.js
Labels: docs, maintenance
